import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import React, { FC, PropsWithChildren } from 'react'

import ClientProvider from '@/components/providers/client.provider'
import { cn } from '@/lib/utils'

const font = Montserrat({
	subsets: ['latin', 'vietnamese']
})

export const metadata: Metadata = {
	title: 'Ruby Lucky',
	description: 'Generated by create next app'
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang="en">
			<body className={cn(font.className, 'antialiased')}>
				<ClientProvider>{children}</ClientProvider>
			</body>
		</html>
	)
}

export default RootLayout
